event_fetchAll:
    path: /events
    controller: App\Controller\Event\Get::fetchAll
    methods: [GET]

event_fetch:
    path: /events/{id}
    controller: App\Controller\Event\Get::fetch
    methods: [GET]
    requirements:
        id: '\d+'
    
event_create:
    path: /events
    controller: App\Controller\Event\Post::create
    methods: [POST]

event_update:
    path: /events/{id}
    controller: App\Controller\Event\Put::update
    methods: [PUT]
    requirements:
        id: '\d+'
    
event_delete:
    path: /events/{id}
    controller: App\Controller\Event\Delete::delete
    methods: [DELETE]
    requirements:
        id: '\d+'