event_fetch_all_by_location:
    path: /locations/{locationId}/events
    controller: App\Controller\Event\Get::fetchAllByLocation
    methods: [GET]

event_fetch:
    path: /events/{eventId}
    controller: App\Controller\Event\Get::fetch
    methods: [GET]
    
event_create:
    path: /locations/{id}/events
    controller: App\Controller\Event\Post::create
    methods: [POST]
       
location_fetch:
    path: /locations/{locationId}
    controller: App\Controller\Location\Get::fetch
    methods: [GET]
         
location_create:
    path: /locations
    controller: App\Controller\Location\Post::create
    methods: [POST]
        