event_fetch_all_by_location:
    path: /locations/{locationId}/events
    controller: App\Controller\Event\Get::fetchAllByLocation
    methods: [GET]
    
event_fetch_all:
    path: /events
    controller: App\Controller\Event\Get::fetchAll
    methods: [GET]

event_fetch:
    path: /events/{eventId}
    controller: App\Controller\Event\Get::fetch
    methods: [GET]
    
event_create:
    path: /locations/{id}/events
    controller: App\Controller\Event\Post::create
    methods: [POST]
       
location_fetch:
    path: /locations/{locationId}
    controller: App\Controller\Location\Get::fetch
    methods: [GET]
         
location_create:
    path: /locations
    controller: App\Controller\Location\Post::create
    methods: [POST]
    
post_fetch_all_by_event:
    path: /events/{eventId}/posts
    controller: App\Controller\Post\Get::fetchAllByEvent
    methods: [GET]
    
post_fetch:
    path: /events/{eventId}/posts/{postId}
    controller: App\Controller\Post\Get::fetch
    methods: [GET]
    
post_create:
    path: /events/{eventId}/posts
    controller: App\Controller\Post\Post::create
    methods: [POST]
        